
import com.mongodb.*;
import java.awt.Color;
import java.awt.Container;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


    /**
 *
 * @author suchita
 */
public class table extends javax.swing.JFrame {

    /**
     * Creates new form table
     */
    public table() {
        initComponents();
        
        getContentPane().setBackground(Color.red); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 100, 500, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(255, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "ID", "ADDRESS", "PHONE_NO", "ACC_NO", "PIN_NO", "Balance"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new second1().setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        // TODO add your handling code here: boolean winactivation=false;
           boolean winactivation=false;
     BasicDBObject find;
        DBCursor cursor = null;
        
                 if(winactivation==false)
        {
            winactivation=true;
            
            try
            {
                 Mongo client=new Mongo("localhost",27017);
                 
                 DB db=client.getDB("atm");
                 DBCollection col=db.getCollection("main");
                 

                 
                cursor = col.find();
          
                DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
                dtm.getDataVector().removeAllElements();
                 
                 while(cursor.hasNext())
                 {
                     dtm.addRow( new Object[]{cursor.next().get("name"),
                     cursor.curr().get("id"),
                     cursor.curr().get("add"),
                     cursor.curr().get("phone"),
                     cursor.curr().get("acc"),
                     cursor.curr().get("pin"),
                     cursor.curr().get("balance")});
          
                 }
                 
                 /*int i =table.getRowCount();
                 String g=String.valueOf(i);
                 maxcount.setText(g);*/
            }
            catch(Exception e)
            {     //System.out.println("Connection Failed");
                 JOptionPane.showMessageDialog(rootPane, "Connection Failed");
                 super.dispose();
            }
            finally
            {
                cursor.close();
            } 
            
            
        }        // TODO add your handling code here:
    
     /*BasicDBObject find;
        DBCursor cursor = null;
        
                 if(winactivation==false)
        {
            winactivation=true;
            
            try
            {
                 Mongo client=new Mongo("localhost",27017);
                 
                 DB db=client.getDB("cricket_club");
                 DBCollection col=db.getCollection("batch");
                 

                 
                cursor = col.find();
          
                DefaultTableModel dtm=(DefaultTableModel) table.getModel();
                dtm.getDataVector().removeAllElements();
                 
                 while(cursor.hasNext())
                 {
                     dtm.addRow( new Object[]{cursor.next().get("_id"),
                     cursor.curr().get("name"),
                     cursor.curr().get("lastname"),
                     cursor.curr().get("contact"),
                     cursor.curr().get("batch_type"),
                     cursor.curr().get("batch_timing"),
                     cursor.curr().get("usertype"),
                     cursor.curr().get("calander"),
                     cursor.curr().get("duration")});
          
                 }
                 
                 int i =table.getRowCount();
                 String g=String.valueOf(i);
                 maxcount.setText(g);
            }
            catch(Exception e)
            {     //System.out.println("Connection Failed");
                 JOptionPane.showMessageDialog(rootPane, "Connection Failed");
                 super.dispose();
            }
            finally
            {
                cursor.close();
            } 
            
            
        }  */      // TODO add your handling code here:

    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new table().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
