
import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import java.awt.Color;
import java.awt.HeadlessException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author suchita
 */
public class WITHDROW extends javax.swing.JFrame {
public String uname;
    /**
     * Creates new form WITHDROW
     */
    public WITHDROW() {
        initComponents();
    }

    WITHDROW(String myname) {
        uname=myname;
         initComponents();
         
                getContentPane().setBackground(Color.white);
          }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 100, 400, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("ENTER AMOUNT TO WITHDROW");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(72, 72, 72)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(202, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {
            DB login;
            login = (new MongoClient("localhost",27017)).getDB("atm");
             DBCollection loginCollection;
            loginCollection = login.getCollection("main");
             BasicDBObject searcht=new BasicDBObject();
                
                searcht.put("id", uname);
        DBCursor cursor=loginCollection.find(searcht);
         DBObject obj;
            obj =cursor.next();
                       String i=((String)obj.get("id"));
                       String bal=((String)obj.get("balance"));
                        BasicDBObject new_doc = new BasicDBObject();
                        new_doc.put("balance",bal);
                   int balance=Integer.parseInt(bal); 
                     String check_s2=jTextField1.getText();
                         int amm=Integer.parseInt(check_s2);
            
                         if(amm<=0)
                         {JOptionPane.showMessageDialog(null,"Enter Valid ammount","",JOptionPane.ERROR_MESSAGE);
                        
                         }
                         else if(amm>balance)
                         {
                             JOptionPane.showMessageDialog(null,"Enter Valid ammount","",JOptionPane.ERROR_MESSAGE);
                        
                         }
                         else if( uname.equals(i))
                         {
                            
                             balance= balance-amm;
                             String wbal=Integer.toString(balance);
                             jTextField1.setText(String.valueOf(wbal));
                             String bal1=jTextField1.getText();
                              jLabel2.setText(((String)obj.get("id")));
                              jLabel3.setText(((String)obj.get("name")));
                              jLabel4.setText(((String)obj.get("add")));
                              jLabel5.setText(((String)obj.get("phone")));
                              jLabel6.setText(((String)obj.get("acc")));
                              jLabel7.setText(((String)obj.get("pin")));
                              
                               String id=jTextField1.getText();
                                String id1=jLabel2.getText();
                                 String name=jLabel3.getText();
                                  String add= jLabel4.getText();
                                   String phone= jLabel5.getText();
                                    String acc=jLabel6.getText();
                                    String pin=jLabel7.getText();
                             new_doc.put("balance",bal1);
                             new_doc.put("id",id1);
                             new_doc.put("name",name);
                             new_doc.put("add",add);
                             new_doc.put("phone",phone);
                             new_doc.put("acc",acc);
                             new_doc.put("pin",pin);
                             
                            // wbal=String.parseString(balance);
                             loginCollection.update(new BasicDBObject().append("id",uname),new_doc);
                             //loginCollection.update(new BasicDBObject().append("balance",bal1),);
                             
                           JOptionPane.showMessageDialog(null,"Transaction Successsful!!!!!!");
                            new NewJFrame2(uname).setVisible(true);
                            this.hide();
                         }

            
           /* DBObject dbobject=loginCollection.findOne();
             BasicDBObject obj = new BasicDBObject();
          String check_s2=jTextField1.getText();
            obj.put("balance",check_s2);
           
          
           // search = (String)obj.get("id");
           
             BasicDBObject searcht=new BasicDBObject();
                
                searcht.put("id", uname);
       // DBCursor cursor=loginCollection.find(searcht);
            
         DBObject obj1;
           // obj1 =cursor.next();
               int amm=Integer.parseInt(check_s2);
                   String bal=((String)obj.get("balance"));
                   int balance=Integer.parseInt(bal);
                    if( amm==0)
                    {
                        JOptionPane.showMessageDialog(null,"Enter Valid ammount","",JOptionPane.ERROR_MESSAGE);
                            
                    }
                    else 
                    {
                        balance=balance-amm;
                       
                      /*   BasicDBObject searcht1;
            searcht1= new BasicDBObject(balance);
            loginCollection.update(searcht1);*/
                       /* loginCollection.update(new BasicDBObject().append("id",balance),searcht);
           
          
            JOptionPane.showMessageDialog(null,"Transaction Successsful!!!!!!","",JOptionPane.ERROR_MESSAGE);
                         DBCursor cursor1 = loginCollection.find();
            DBObject db;
            db=cursor1.next();
             
        this.hide();       //        // TODO add your handling code here:
  
                    }  */  

           
         }
        
        catch (NumberFormatException | HeadlessException ex) {
            Logger.getLogger(WITHDROW.class.getName()).log(Level.SEVERE, null, ex);
        }       //        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WITHDROW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WITHDROW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WITHDROW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WITHDROW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new WITHDROW().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
